Update ikra.sh
yyoshiaki/ikra pull request #62
Opened 2021-04-19 04:32 UTC by Ryoka02

gencodeのバージョンを指定するオプションをつけました

2021-04-19 04:42 UTC, yyoshiaki commented on ikra.sh
> +  BASE_REF_TRANSCRIPT=ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M$M_GEN_VER
細かいけど、可読性のために以下のように修正できますか？

```
BASE_REF_TRANSCRIPT=ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M${M_GEN_VER}
```

2021-04-19 04:42 UTC, yyoshiaki requested changes
変数の書き方だけ修正お願いします！

2021-04-19 05:22 UTC, Ryoka02 commented
修正しました、ご指摘ありがとうございます！

2021-04-19 07:24 UTC, yyoshiaki commented
テスト通りました！
READMEも更新してもらえますか？

2021-04-20 03:07 UTC, Ryoka02 commented
READMEを更新しました。不足等あればお手数ですがお知らせください。

2021-04-20 04:42 UTC, merged

2021-04-20 04:42 UTC, yyoshiaki commented
Great job!